export const AFFILIATIONS = [
	// Factions
	'The Clan of the Thundering Herd',
	'The Order of the Black Sepulcher',
	'The Crimson Banner Company',
	'The Sularian Crosstraders',
	'The Gilded Court',
	'The Brotherhood of Salt',
	'Byrgenwyrth',
	'Bohen Dur',
	// Current Reigning powers
	'The Cranium Cabal',
	'The Tharsang Empire',
	'The Shadowfeather Covenant',
	// Forgotten Gods
	'Heralds of Chaldaroth',
	'The Sularian Church',
	'The Oram Hai',
	"Xethys' Concealing Feathers",
	"Stewards of Arcane Consumption",
	"Damani's Curtisans",
	'The Children of the Sun',
	"The Artisans of Archenthios",
	"The Wind-Whisperers of Fiunurr",
	// Cities & Regions
	'Sargrad',
	'Innis',
	'Ursalis',
	'Tarasrael',
	'Harunkaray',
	'Tiste Andii',
	'Hamoratt',
	'Orinfell',
	'Lawbrand',
	'Chu-Ta, Realm of Heavens',
	'The Truhaldener Forest',
	'The Padurnic Vale',
	'Cimitir, the Undying Lands',
];
