export const EXPERIENCES: string[] = [
	'Raised Among Grave-Moss',
	'Once Betrayed a Patron Saint',
	'Knows the Taste of Black Powder',
	'Buried a Sibling in Secret',
	'Spoke With a Dying God',
	'Fled a Burning Monastery',
	'Was Hunted for Heresy',
	'Carved Oaths Into Bone',
	'Survived the Plague Bells',
	'Walked the Ashen Frontier',
	'Survivor of the Black Harvest',
	'I lit the pyres at Hollowmere',
	'Branded Oathbreaker of the Iron Host',
	'Last Knight of a Shattered Banner',
	'Gravekeeper During the Red Fever',
	'Torturer Who Finally Spoke',
	'Bastard of a War Criminal',
	'Veteran of the Hopeless Charge',
	'Executioner Who Refused a Child',
	'Chronicler of Atrocities',
	'Plague Cart Driver, Still Unclaimed',
	'Deserter from the Ash Legion',
	'Raised Among Gallows and Crows',
	'Confessor to Dying Soldiers',
	'Burned by Witchfire, Still Living',
	'Keeper of Mass Graves',
	'Mercenary of the Broken Pact',
	'Orphan of the Salted Fields',
	'Knight Stripped of Heraldry',
	'Survivor of Friendly Fire',
	'Witness to a False Miracle',
	'Butcher of a Starving Winter',
	'Bearer of a Cursed Standard',
	'Bodyguard to a Tyrant',
	'Child of the Burning Chapel',
	'Poison Taster Who Lived',
	'Last Voice of a Doomed Rebellion',
	'Exile from Blightmarsh',
	'Graverobber Turned Reluctant Exorcist',
	'Soldier Who Ate the Siege',
	'Failed Crusader of the Pale Sun',
	'Watcher on the Corpse Shore',
	'Confidant of a Mad Inquisitor',
	'Bound to a Dead God',
	'Survivor of Ritual Betrayal',
	'Hangman’s Apprentice',
	'Shieldmate to a Fallen Hero',
	'Raised in a Prison Camp',
	'Scarred by Demon Occupation',
	'Bearer of Unpaid Blood Debt',
	'Veteran of Endless Trenches',
	'Sole Survivor of Blackridge',
	'Accused Heretic of Stonefall',
	'Temple Defiler, Unrepentant',
	'Witch-Hunter Without Faith',
	'Slayer of a Surrendering Foe',
	'Archivist of Forbidden Testimonies',
	'Survivor of Cannibal Winter',
	'Standard-Bearer at Last Stand',
	'Gravedigger for a Doomed City',
	'Broken Paladin of Ashen Oaths',
	'Court-Martialed Captain',
	'Keeper of the Execution Ledger',
	'Flagellant Zealot',
	'Smuggler of Holy Relics',
	'Interrogator Who Heard Too Much',
	'Fugitive from the Black Tribunal',
	'Knight of a Silent Order',
	'Survivor of Plague Riots',
	'Confessor of Regicidal Secrets',
	'Haunted Siege Engineer',
	'Bearer of a Blighted Sigil',
	'Guard of a Fallen Gate',
	'Chapel Warden During Massacre',
	'Herald of False Peace',
	'Soldier Branded Traitor',
	'Scavenger of Battlefields',
	'Veteran of Broken Treaties',
	'Raised by Camp Followers',
	'Execution Witness Turned Rebel',
	'Keeper of the Ash Reliquary',
	'Survivor of a Failed Resurrection',
	'Mercy Killer at Duskfall',
	'Black Banner Standard-Bearer',
	'Shieldbreaker of Greywatch',
	'Child Soldier of Ironvale',
	'Deserter Who Saved Civilians',
	'Famine Forager of Deadlands',
	'Torched My Own Village',
	'Watcher Beneath Gallows Hill',
	'Former Cult Enforcer',
	'Bearer of an Unholy Brand',
	'Chronicler of Lost Causes',
	'Guardian of the Final Refuge',
	'Prison Interrogator Turned Penitent',
	'Scion of a Ruined House',
	'Knight Who Refused the Charge',
	'Raised Among Executioners',
	'Refugee of the Blood March',
	'Grave Sentinel at Dawn',
	'Veteran of Nameless Wars',
	'Bearer of a Shattered Oath',
	'Survivor of Cathedral Slaughter',
	'Confessor to the Condemned',
	'Excommunicated Battle Priest',
	'Keeper of the Bone Pit',
	'Witness to God’s Silence',
	'Soldier of a Lost Empire',
	'Marshal of a Dead Town',
	'I Shot a Man Who Rose',
	'Railroad Engineer Who Dug Too Deep',
	'Desert Visionary with Burning Eyes',
	'Bounty Hunter of the Unnatural',
	'Telegraph Operator Hearing Voices',
	'Snake-Oil Salesman with Real Magic',
	'Survivor of the Vanished Settlement',
	'Gunsmith for the Damned',
	'Preacher Who Buried His Faith',
	'Prospector Who Struck Bone',
	'Deputy Who Knew the Truth',
	'Undertaker of Restless Graves',
	'Rider Through Cursed Canyon',
	'Ex-Pinkerton Occultist',
	'Saloon Pianist Playing Ritual Hymns',
	'Tracker of Skinwalkers',
	'Riverboat Gambler Seeing Futures',
	'Stagecoach Guard at Sundown',
	'Ranch Hand Who Branded a Demon',
	'Outlaw Bound by Ghost Oath',
	'Tribal Mystic in Exile',
	'Lawman with a Dead Partner',
	'Miner Who Found Something Watching',
	'Sharpshooter Marked by Spirits',
	'Cemetery Caretaker After Midnight',
	'Snake-Handling Revivalist',
	'Bandit Who Spared the Witch',
	'Border Ranger Against Nightfall',
	'Cattleman Who Fought the Wind',
	'Ghost-Town Schoolteacher',
	'Drifter with a Spirit Guide',
	'Whiskey Runner for Revenants',
	'Deputy of the Hollow Badge',
	'Railworker Who Hammered Curses',
	'Town Doctor Studying the Unquiet',
	'Frontier Midwife of Strange Births',
	'Stage Magician Using Real Spells',
	'Desert Hermit Seeing Portents',
	'Rode with a Witch Outlaw',
	'Bank Guard During Haunting',
	'Sharpshooter of the Pale Moon',
	'Gold Rush Survivor of Shadows',
	'Saloon Owner with Hidden Sigils',
	'Marshal Who Closed Hell’s Door',
	'Telegraph Clerk at Witching Hour',
	'Tracker of Unmarked Graves',
	'Train Robber with Sacred Bullets',
	'Missionary Among Spirits',
	'Outlaw Preacher of Dust',
	'Ferry Operator Across Dark Waters',
	'Deputy Who Shot a Possessed Man',
	'Cowpoke Who Heard the Earth',
	'Graveyard Duelist at High Noon',
	'Rail Baron’s Disgraced Agent',
	'Prospector Guarding a Cursed Claim',
	'Desert Scout of the Spirit Trail',
	'Gunslinger Bound to a Totem',
	'Underground Fighter in Silver City',
	'Caravan Guard in Haunted Pass',
	'Ex-Soldier of Forgotten Skirmish',
	'Snake Charmer of Badwater',
	'Surveyor Mapping Forbidden Ground',
	'Deputy During the Long Night',
	'Saloon Girl Seeing True Faces',
	'Buffalo Hunter of Bone Plains',
	'Marshal of Black Mesa',
	'Card Shark Cheating Fate',
	'Windmill Keeper Hearing Whispers',
	'Border Smuggler of Relics',
	'Stagecoach Driver Through Phantom Ridge',
	'Outlaw Who Killed a Revenant',
	'Town Drunk Who Saw Too Much',
	'Ranger Who Sealed a Mine',
	'Prospector with Silvered Pickaxe',
	'Reverend of the Dust Choir',
	'Telegraph Rider in Stormlight',
	'Sharpshooter at Devil’s Crossing',
	'Cattle Rustler of the Damned Herd',
	'Tracker Following Invisible Trails',
	'Midnight Duel Survivor',
	'Railway Guard Against Night Riders',
	'Snakebite Healer of Red Gulch',
	'Ghostlight Witness in Drywater',
	'Deputy of Broken Spur',
	'Grave Marker Carver',
	'Saloon Brawler at Witching Hour',
	'Frontier Orphan of Ash Creek',
	'Outlaw Bride of Shadow Mesa',
	'Ranch Foreman Who Saw Leviathans',
	'Desert Scout of Lost Wells',
	'Stage Performer Summoning Applause',
	'Gunslinger at Sundown Ridge',
	'Miner Trapped Beneath Whispers',
	'Marshal Who Faced the Pale Rider',
	'Riverboat Pilot on Black Current',
	'Town Founder Who Knew the Cost',
	'Border Rider at Twilight',
	'Disgraced Diplomat of Sapphire Court',
	'I Delivered the Letter That Burned',
	'Royal Spymaster’s Unclaimed Apprentice',
	'Bastard Heir No One Names',
	'Keeper of the Secret Ledger',
	'They Married Me for Peace',
	'Witness to the King’s Poisoning',
	'Blackmail Archivist of Three Houses',
	'Court Jester Who Heard Everything',
	'Envoy to a Hostile Throne',
	'Advisor to a Failing Regent',
	'Architect of a Quiet Coup',
	'Bearer of Forged Lineage',
	'Hostage Raised Among Enemies',
	'Chamberlain of Whispered Deals',
	'Confessor to the Queen',
	'Master of Discreet Assassins',
	'Clerk Who Altered the Treaty',
	'Ambassador in Exile',
	'Guardian of the Royal Seal',
	'Spouse in a Strategic Marriage',
	'Envoy Who Switched Allegiance',
	'Chronicler of Court Scandals',
	'Senator with Purchased Votes',
	'Shadow Broker of Alliances',
	'Servant of Two Crowns',
	'Witness to Midnight Negotiations',
	'Envoy Bearing False Promises',
	'Counselor to a Mad Prince',
	'Protege of a Fallen Chancellor',
	'Architect of Election Fraud',
	'Royal Food Taster',
	'Bearer of Secret Correspondence',
	'Exiled Heir to Parliament',
	'Keeper of the Crown Jewels',
	'Attendant at the Silent Conclave',
	'Advisor Who Leaked the Truth',
	'Messenger of Sealed Decrees',
	'Financier of a Rebellion',
	'Negotiator of Prisoner Exchanges',
	'Confidant of the Dowager Queen',
	'Seneschal of the Northern March',
	'Royal Body Double',
	'Scholar of Succession Laws',
	'Custodian of State Secrets',
	'Spymaster’s Field Agent',
	'Chronicler of Treason Trials',
	'Envoy to the Border Lords',
	'Advocate for the Unpopular Cause',
	'Patron of Hidden Guilds',
	'Recorder of Secret Votes',
	'Master of Ceremonial Lies',
	'Broker of Marriage Contracts',
	'Keeper of Illicit Letters',
	'Observer at Peace Talks',
	'Counselor During Regency Crisis',
	'Secretary to the War Council',
	'Envoy Bearing Hostage Terms',
	'Senator Under Investigation',
	'Clerk Who Hid the Evidence',
	'Royal Librarian of Forbidden Acts',
	'Architect of Trade Embargo',
	'Watcher in the Gallery',
	'Adopted Child of Nobility',
	'Envoy Who Misspoke Intentionally',
	'Negotiator with Pirate Lords',
	'Custodian of Diplomatic Immunity',
	'Adviser on Succession Disputes',
	'Guardian of the Treasury Vault',
	'Confessor to a Traitor',
	'Emissary from the Frontier',
	'Clerk Who Misfiled a Decree',
	'Architect of Propaganda',
	'Master of Court Etiquette',
	'Shadow Auditor of Accounts',
	'Observer at Secret Trials',
	'Advisor to the Rebel Faction',
	'Royal Messenger Through Warzones',
	'Chronicler of Parliamentary Chaos',
	'Custodian of Royal Archives',
	'Ambassador to the Faithful',
	'Counselor During Famine Riots',
	'Negotiator of Hostile Ceasefire',
	'Servant in the Privy Chamber',
	'Envoy Bearing Ultimatums',
	'Protector of a Compromised Heir',
	'Spouse to a Rival House',
	'Financier of Foreign Interests',
	'Guardian of the Regency Council',
	'Recorder of Oaths',
	'Adviser on Military Funding',
	'Scholar of Political Heresies',
	'Clerk in the Intelligence Bureau',
	'Observer of Closed Sessions',
	'Architect of Quiet Reform',
	'Confidant of the Crown Prince',
	'Envoy to the Secret Compact',
	'Custodian of Diplomatic Codes',
	'Broker of Silent Alliances',
	'Apprentice Necromancer of Black Spire',
	'I Opened the Sealed Door',
	'Moon-Marked Wanderer',
	'Bound to a Whispering Shadow',
	'Village Witch’s Last Apprentice',
	'The Forest Knows My Name',
	'Failed Vessel of a Dark God',
	'Relic Keeper Who Cannot Lose It',
	'Dream-Walker Between Worlds',
	'Survivor of the Summoning Circle',
	'Bearer of a Living Curse',
	'Scholar of Forbidden Tomes',
	'Guardian of the Hollow Shrine',
	'Marked by Fey Bargain',
	'Watcher at the Witchlight',
	'Child Touched by the Veil',
	'Lantern Bearer in Endless Mist',
	'Seeker of Lost Grimoires',
	'Disciple of a Fallen Archmage',
	'Keeper of the Bone Orchard',
	'Exorcist Who Doubts',
	'Bearer of a Cursed Crown',
	'Chosen by a Silent Deity',
	'Warden of the Shadow Gate',
	'Midnight Herbalist of Thornwood',
	'Guardian of a Sleeping Horror',
	'Bloodline of Forgotten Sorcerers',
	'Watcher of the Black Tower',
	'Bound to a Spirit Familiar',
	'Seer of Drowned Visions',
	'Ritualist of Broken Circles',
	'Keeper of the Silver Sigil',
	'Child of the Eclipse',
	'Scholar of Demonology',
	'Bearer of a Haunted Blade',
	'Initiate of the Veiled Order',
	'Watcher Beneath the Chapel',
	'Marked by Starfall',
	'Exile from the Fey Court',
	'Collector of Cursed Relics',
	'Warden of the Misty Barrow',
	'Herald of a Dark Prophecy',
	'Bearer of Ashen Wings',
	'Seeker of Lost Names',
	'Keeper of the Obsidian Key',
	'Guardian of Forbidden Catacombs',
	'Disciple of the Bone Choir',
	'Marked by Witchfire',
	'Watcher at the World’s Edge',
	'Bearer of a Living Grimoire',
	'Seer Beneath Blood Moon',
	'Guardian of the Thorn Gate',
	'Scholar of Eldritch Runes',
	'Bound to a Dreaming Entity',
	'Warden of Forgotten Crypts',
	'Chosen by the Hollow Star',
	'Initiate of Shadow Rites',
	'Keeper of the Withered Grove',
	'Bearer of Spirit Chains',
	'Watcher of the Pale Lake',
	'Disciple of the Night Mother',
	'Herald of the Dying Sun',
	'Guardian of the Broken Circle',
	'Seeker of Phantom Cities',
	'Marked by Raven Queen',
	'Bearer of the Black Lantern',
	'Warden of the Hidden Vault',
	'Scholar of Ancient Pacts',
	'Chosen by Whispering Woods',
	'Keeper of the Crimson Reliquary',
	'Watcher at Moonlit Crossroads',
	'Disciple of the Veiled Prophet',
	'Bearer of a Sealed Fate',
	'Guardian of the Shattered Idol',
	'Seer of the Hollow Sky',
	'Warden of Eldritch Thresholds',
	'Initiate of Bone Sigils',
	'Keeper of Forgotten Altars',
	'Marked by Runebound Curse',
	'Herald of the Gloam Court',
	'Bearer of the Twilight Brand',
	'Watcher Beneath Root and Stone',
	'Scholar of Lost Constellations',
	'Chosen by the Abyssal Choir',
	'Guardian of Spirit Wells',
	'Seeker of Hidden Sanctums',
	'Warden of the Black Orchard',
	'Disciple of Silent Choirs',
	'Bearer of the Veilmark',
	'Watcher of Shifting Shadows',
	'Keeper of the Night Archive',
	'Initiate of Forbidden Psalms',
	'Marked by Hollow Crown',
	'Guardian of Dreaming Barrows',
	'Seer of the Final Dawn',
	'Bearer of the Umbral Sigil',
	'Warden of Forgotten Doors',
	'Child of the Witchwood'
];
