import type { TableEntry } from '../moves/miracles/tables';

export const EFFECT: TableEntry[] = [
	'Absorbing ',
	'Infecting',
	'Accelerating ',
	'Intoxicating',
	// replacing activity
	'Activating',
	'Irradiating',
	'Amusing ',
	'Irritating',
	'Animating ',
	'Levitating',
	'Armoring ',
	'Liquefying',
	'Attracting ',
	'Maddening',
	'Avenging ',
	'Menacing',
	'Awakening ',
	'Mending',
	'Banishing ',
	'Mesmerizing',
	'Beautifying ',
	'Mindreading',
	'Bewildering ',
	'Mocking',
	'Binding ',
	'Monitoring',
	'Blinding ',
	'Multiplying',
	'Blossoming ',
	'Mutating',
	'Burning ',
	'Nauseating',
	'Charming ',
	'Nullifying',
	'Cleansing ',
	'Pacifying',
	'Commanding ',
	'Persuading',
	'Communicating ',
	'Petrifying',
	'Concealing ',
	'Piercing',
	'Condemning ',
	'Preserving',
	'Corroding ',
	'Pummeling',
	'Corrupting ',
	'Putrefying',
	'Crushing ',
	'Reflecting',
	'Darkening ',
	'Refreshing',
	'Dazzling ',
	'Regenerating',
	'Deafening ',
	'Repelling',
	'Deciphering ',
	'Retrieving',
	'Diminishing ',
	'Revealing',
	'Disguising ',
	'Saddening',
	'Dispelling ',
	'Sanctifying',
	'Draining ',
	'Scrying',
	'Duplicating ',
	'Sealing',
	'Electrifying ',
	'Shielding',
	'Emboldening ',
	'Silencing',
	'Enraging ',
	'Slicing',
	'Enticing ',
	'Spawning',
	'Etherealizing ',
	'Stinging',
	'Excruciating ',
	'Strangling',
	'Expanding ',
	'Summoning',
	'Foreseeing ',
	'Teleporting',
	'Freezing ',
	'Terrifying',
	'Fusing ',
	'Transmuting',
	'Hardening ',
	{ table: 'trapEffect' },
	'Haunting ',
	'Transporting',
	'Healing ',
	'Vaporizing',
	'Identifying ',
	'Warding',
	'Illuminating ',
	'Wearying',
	'Imprisoning ',
	'Withering'
];
