import type { TableEntry } from "../moves/miracles/tables";

export const ELEMENT: TableEntry[] = [

    "Acid", { table: "material" },
    "Amber", "Memory",
    "Ash", "Miasma",
    "Beer", "Moss",
    "Bile", "Mud",
    "Blood", "Nectar",
    "Blossom", "Oatmeal",
    "Bone", "Obsidian",
    "Brass", "Oil",
    "Brimstone", "Paint",
    "Brine", "Paper",
    "Butter", "Perfume",
    "Chalk", "Plague",
    "Chaos", "Poison",
    "Clay", "Pollen",
    "Cloud", "Quicksilver",
    "Cold", "Radiation",
    "Crystal", "Rain",
    "Darkness", "Root",
    "Death", "Rot",
    { table: "domain" }, "Salt",
    "Dream", "Sand",
    "Dust", "Sap",
    { table: "fabric" }, "Shadow",
    "Flame", "Silk",
    "Flesh", "Slime",
    "Foam", "Smoke",
    "Fog", "Snow",
    { table: "food" }, "Soot",
    "Frost", "Spark",
    "Fume", "Speed",
    "Fungus", "Spore",
    "Ghost", "Steam",
    "Glass", "Stench",
    "Glue", "Stone",
    "Gravel", "Storm",
    "Hail", "Sugar",
    "Heat", "Syrup",
    "Honey", "Taffy",
    "Ice", "Tar",
    "Incense", "Tea",
    "Ink", "Tears",
    "Iron", "Thorn",
    "Ivory", "Vine",
    "Lava", "Void",
    "Lead", "Water",
    "Leaf", "Wax",
    "Light", "Wind",
    "Lightning", "Wine",
    "Marmalade", "Wood",
];