import type { TableEntry } from "../moves/miracles/tables";

export const FOOD: TableEntry[] = [
    "Acorn ", "Kidney bean",
    "Alligator ", "Lamb",
    "Almond ", "Leek",
    { table: 'animal' }, "Lemon",
    "Antelope ", "Lime",
    "Apple ", "Lobster",
    "Artichokes ", "Moose",
    "Asparagus ", { table: "monster" },
    "Bass ", "Mushroom",
    "Bear ", "Mussels",
    "Beaver ", "Mutton",
    "Beef ", "Onion",
    "Beet ", "Orange",
    "Bell pepper", { table: "organ" },
    "Bison ", "Partridge",
    "Blueberry ", "Pea",
    "Broccoli ", "Pear",
    "Brussels sprout", "Perch",
    "Cabbage ", "Pheasant",
    "Carp ", "Pork",
    "Carrot ", "Possum",
    "Catfish ", "Potato",
    "Cattail ", "Pumpkin",
    "Cauliflower ", "Quail",
    "Caviar ", "Rabbit",
    "Celery ", "Raccoon",
    "Cheese ", "Radish",
    "Cherry ", "Raspberry",
    "Chestnut ", "Rat",
    "Chicken", "Reindeer",
    "Clams ", "Rhubarb",
    "Corn ", "Salmon",
    "Crab ", "Shrimp",
    "Crayfish ", "Snails",
    "Cucumber ", "Snake",
    "Dandelion ", "Spinach",
    "Duck ", "Squash",
    "Eel ", "Squirrel",
    "Egg ", "Strawberry",
    "Eggplant ", "Sturgeon",
    "Elk ", "Tangerine",
    "Goat ", "Tomato",
    "Goose ", "Trout",
    "Grape ", "Turnip",
    "Green bean", "Turtle",
    "Guinea pig", "Veal",
    "Ham ", "Venison",
    "Hare ", "Walnut",
    "Hazelnut ", "Wild boar",
    "Hot pepper", "Yam",
]