import type { TableEntry } from '../moves/miracles/tables';

export const MATERIAL: TableEntry[] = [
	'Adamantine',
	'Mammoth tusk',
	'Alabaster',
	'Moonstone',
	'Amber',
	'Morganite',
	'Ambergris',
	'Moss agate',
	'Aquamarine',
	'Mother of pearl',
	'Aventurine',
	'Narwhal horn',
	'Azurite',
	'Nephrite',
	'Beryl',
	'Obsidian',
	'Black alabaster',
	' Onyx',
	'Black opal',
	' Orichalcum',
	'Black pearl',
	' Palladium',
	'Bloodstone',
	'Pearl',
	'Bloodwood',
	'Peridot',
	'Blue amber',
	' Petrified wood',
	'Blue jade',
	' Pink sapphire',
	'Blue opal',
	' Platinum',
	'Bone china',
	' Polyhedroid agate',
	'Cairngorm',
	'Porcelain',
	'Carbuncle',
	'Porcelain jasper',
	'Carnelian',
	'Porphyry',
	'Cat’s-eye',
	' Purpleheart wood',
	'Chalcedony',
	'Quartz',
	'Cherry amber',
	' Quetzal jade',
	'Cinnabar',
	'Rainbow agate',
	'Citrine',
	'Rainbow jasper',
	'Crystal',
	'Rainbow obsidian',
	'Cyclops agate',
	' Redheart wood',
	'Dendritic agate',
	' Rose opal',
	'Diamond',
	'Rose quartz',
	'Dragon bone',
	' Rosewood',
	'Ebony',
	'Ruby',
	'Emerald',
	'Sandalwood',
	'Fire agate',
	' Sapphire',
	'Fire coral',
	' Sard',
	'Fire jasper',
	' Serpentine',
	'Fire opal',
	' Silver',
	'Garnet',
	'Snakewood',
	'Gold',
	'Spinel',
	'Heliodor',
	'Star Iron',
	'Hematite',
	'Star rose quartz',
	'Horn',
	'Star sapphire',
	'Ironwood',
	'Sunstone',
	'Jet',
	'Tiger’s eye',
	'Kingfisher jade',
	' Tigerwood',
	'Koa wood',
	' Topaz',
	'Lapis lazuli',
	' Tourmaline',
	'Lavender jade',
	' Turquoise',
	'Lingum vitae',
	' Turtle shell',
	'Mahogany',
	'Unicorn horn',
	'Malachite',
	'Whale ivory'
];
