import type { TableEntry } from "../moves/miracles/tables";

export const PLACE_TRAIT: TableEntry[] = [
    "Ashen", "Loathsome",
    "Bewitching", "Mechanical",
    "Black", "Misty",
    "Blessed", "Murmuring",
    "Blighted", "Mysterious",
    "Bloody", "Oozing",
    "Boiling", "Overgrown",
    "Bright", "Perilous",
    "Broken", "Petrified",
    "Buried", "Phantasmal",
    "Burning", "Phasing",
    "Charred", "Pristine",
    "Collapsed", { table: "quality" },
    { table: "color" }, "Ravaged",
    "Crawling", "Ravenous",
    "Crimson", "Restless",
    "Crumbling", "Revered",
    "Crystalline", "Destroyed", // replaced RoomTheme
    "Cursed", "Savage",
    "Dark", "Scorching",
    "Dead", "Screaming",
    "Desolate", "Shadowy",
    "Disorienting", "Shifting",
    "Divine", "Shivering",
    "Doomed", "Shrouded",
    "Echoing", "Silent",
    "Eerie", "Singing",
    { table: "effect" }, "Sinister",
    "Elder", "Sinking",
    "Eldritch", "Sleeping",
    { table: "element" }, { table: "sound" },
    "Endless", "Stony",
    "Filthy", "Sunken",
    "Flooded", "Swamped",
    "Forbidden", "Swarming",
    "Forgotten", "Sweltering",
    "Frozen", "Terrifying",
    "Ghostly", { table: "texture" },
    "Glittering", "Thorny",
    "Gloomy", "Thundering",
    "Grim", "Twisting",
    "Haunted", "Unquiet",
    "Hidden", "Vandalized",
    "Holy", "Vast",
    "Humid", "Watching",
    "Infernal", "Whispering",
    "Infested", "Windy",
    "Jagged", "Withered",
    "Labyrinthine", "Wondrous",
    "Living", "Writhing",
]