import type { TableEntry } from "../moves/miracles/tables";

export const SCENT: TableEntry[] = [
    "Acid ", "Licorice",
    "Alcohol ", "Lysol",
    "Almond ", "Manure",
    "Ammonia ", "Medicinal",
    { table: "animal" }, "Mildew",
    "Baby ", "Mint",
    "Balsamic ", "Mold",
    "Banana ", "Musk",
    "Barnyard ", "Nutmeg",
    "Bitter ", "Old books",
    "Blood ", "Old socks",
    "Bread dough", "Olive oil",
    "Brine ", "Onion",
    "Burnt hair", "Orange",
    "Burnt plastic", "Ozone",
    "Burnt rubber", "Paint",
    "Burnt sugar", "Peanut butter",
    "Burnt toast", "Peat moss",
    "Caramel ", "Pine",
    "Cedarwood ", "Pineapple",
    "Cherry ", "Popcorn",
    "Chlorine ", "Rain",
    "Chocolate ", "Resinous",
    "Cigarette ash", "Rose",
    "Coffee ", "Rotten eggs",
    "Cologne ", "Rotten meat",
    "Cookies ", "Rotting fruit",
    "Coppery ", "Seaweed",
    "Cut grass", "Sewer",
    "Damp", "Skunk",
    "Dog breath", "Sour milk",
    "Dumpster ", "Spicy",
    "Earth ", "Spruce",
    { table: 'element' }, "Stagnant",
    "Exhaust ", "Stale beer",
    "Fish ", "Stinky cheese",
    { table: "food" }, "Sulfur",
    "Formaldehyde ", "Sweat",
    "Garlic ", { table: 'taste' },
    "Gasoline ", "Tea",
    "Ginger ", "Thyme",
    "Gunpowder ", "Tobacco",
    "Hamster cage", "Turpentine",
    "Hay ", "Vanilla",
    "Herbal ", "Vinegar",
    "Honey ", "Violets",
    "Hops ", "Vomit",
    "Incense ", "Wet cardboard",
    "Leather ", "Wet dog",
    "Lemon ", "Wood smoke",
]