import type { TableEntry } from "../moves/miracles/tables";

export const SYMBOL: TableEntry[] = [
    { table: 'animal' }, "Key",
    "Antlers", "Knot",
    "Arrow", "Lamp",
    "Axe", "Leaf",
    "Bear", "Lightning bolt",
    "Bell", "Lock",
    "Bird", "Mask",
    "Blood drop", "Map", // replaced miscItem
    "Book", "Moon",
    "Boots", "Nut",
    "Bow", "Octopus",
    "Bowl", { table: 'organ' },
    "Branch", "Ox",
    "Brazier", "Pen",
    "Cauldron", "Pincer",
    "Chain", "Pine cone",
    "Chariot", "Planet",
    "Circle", "Rabbit",
    { table: 'clothing' }, "Rat",
    "Cloud", "Ring",
    "Coin", "Scorpion",
    "Constellation", "Scales",
    "Crab", "Scroll",
    "Cross", "Serpent",
    "Crown", "Shield",
    "Crystal", "Sickle",
    "Dagger", "Skull",
    "Deer", "Snail",
    "Dice", "Snowflake",
    "Eye", "Spear",
    "Fangs", "Spiral",
    "Feather", "Square",
    "Fish", "Staff",
    "Fist", "Star",
    "Flower", "Sun",
    "Fountain", "Sword",
    { table: 'food' }, "Tentacle",
    { table: 'form' }, "Throne",
    "Fox", "Tooth",
    "Frog", "Torch",
    "Gate", "Tree",
    "Goat", "Triangle",
    "Hammer", "Turtle",
    "Hand", "Wave",
    "Heart", { table: 'weapon' },
    "Helmet", "Web",
    "Hook", "Whale",
    "Horn", "Whip",
    "Horse", "Wings",
    "Hourglass", "Wolf",
]