import type { TableEntry } from "../moves/miracles/tables";

export const TRAP_EFFECT: TableEntry[] = [
    "Absorbing", "Oscillating",
    "Accelerating", "Piercing",
    "Arranging", "Pinching",
    "Attracting", "Pointing",
    "Balancing", "Poking",
    "Beating", "Pulling",
    "Bending", "Pushing",
    "Blocking", "Reflecting",
    "Blowing", "Releasing",
    "Bludgeoning", "Removing",
    "Boiling", "Repelling",
    "Burning", "Rolling",
    "Bursting", "Scooping",
    "Burying", "Scrambling",
    "Catching", "Severing",
    "Charging", "Shaking",
    "Choking", "Shocking",
    "Closing", "Shooting",
    "Compressing", "Shredding",
    "Contracting", "Sifting",
    "Counting down", "Sinking",
    "Crushing", "Slashing",
    "Deafening", "Sliding",
    "Delivering", "Slowing",
    // replaced delve shifts
    "Delving", "Smothering",
    "Desiccating", "Soaking",
    "Dividing", "Softening",
    "Draining", "Spinning",
    "Dropping", "Squeezing",
    { table: "effect" }, "Staining",
    "Expanding", "Sticking",
    "Extending", "Stretching",
    "Filling", "Swinging",
    "Flapping", "Tangling",
    "Floating", "Tearing",
    "Focusing", "Tightening",
    "Freezing", "Tilting",
    "Grabbing", "Toppling",
    "Hardening", "Transporting",
    "Hooking", "Tripping",
    "Immobilizing", "Turning",
    "Imprisoning", "Twisting",
    "Inflating", "Unbalancing",
    "Inserting", "Unearthing",
    "Launching", "Unlocking",
    "Lifting", "Weighing",
    "Locking", "Whipping",
    "Loosening", "Winding",
    "Lowering", "Wobbling",
    "Opening", "Wrapping",
]