import type { TableEntry } from "../moves/miracles/tables";
import { generateSurname } from "./surnames";


export const WIZARDNAMES: TableEntry[] = [
    "Abrogast", "Mizisto",
    "Angvar", "Mordandred",
    "Armolok", "Nazmok",
    "Asterwin", "Nobtrik",
    "Azerphon", "Nothry",
    "Barbaloff", "Noonund",
    "Boglin", "Nizmo",
    "Borgarot", "Obrigal",
    "Byzby", "Ornoza",
    "Candula", "Osrat",
    "Chalgot", "Otilix",
    "Cronibal", "Pandelo",
    "Cydinax", "Panderbal",
    "Darj", "Perdeo",
    "Dormog", "Pevin",
    "Dregwith", "Quartat",
    "Dulzant", "Quasmir",
    "Elmeer", "Quilian",
    "Eofast", "Quinfan",
    "Felonse", "Roshmor",
    "Fenundor", "Rudishan",
    "Folgun", "Rumalto",
    "Gelonvir", "Sekeen",
    "Garzant", "Sivinez",
    "Gathifex", "Snilimar",
    "Gilux", "Sofnu",
    "Gyodo", {generator: generateSurname},
    "Hashman", "Tasham",
    "Helkhal", "Hetemtul", "Tenat",
    "Hoonai", "Turminster",
    "Ifit", "Ukanel",
    "Ildefad", "Umbalem",
    "Imzirian", "Uneni",
    "Irolo", "Urokar",
    "Jorkhal", "Vanceus",
    "Jorphdan", "Vermulsin",
    "Kaldash", "Voriel",
    "Karneblin", "Wallester",
    "Kirtep", "Wenton",
    "Kisdal", "Wiltrik",
    "Krolgo", "Xedu",
    "Leodelf", "Xepheran",
    "Lexikrin", "Xolark",
    "Lestin", "Yamorthrax",
    "Lomard", "Yandant",
    "Majdin", "Zanuptra",
    "Mazifant", "Zarugaz",
    "Melkash", "Zilik",
];